name: MSSP-frontend-CI-CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm install

      - name: Set ENV variables based on branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "VITE_APP_NAME=${{ vars.VITE_APP_NAME_DEV }}" >> $GITHUB_ENV
            echo "VITE_APP_URL=${{ vars.VITE_APP_URL_DEV }}" >> $GITHUB_ENV
            echo "VITE_API_URL=${{ vars.VITE_API_URL_DEV }}" >> $GITHUB_ENV
            echo "VITE_USER_POOL_ID=${{ vars.VITE_USER_POOL_ID_DEV }}" >> $GITHUB_ENV
            echo "VITE_CLIENT_ID=${{ vars.VITE_CLIENT_ID_DEV }}" >> $GITHUB_ENV
            echo "VITE_API_WS_URL=${{ vars.VITE_API_WS_URL_DEV }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/demo" ]]; then
            echo "VITE_APP_NAME=${{ vars.VITE_APP_NAME_STG }}" >> $GITHUB_ENV
            echo "VITE_APP_URL=${{ vars.VITE_APP_URL_STG }}" >> $GITHUB_ENV
            echo "VITE_API_URL=${{ vars.VITE_API_URL_STG }}" >> $GITHUB_ENV
            echo "VITE_USER_POOL_ID=${{ vars.VITE_USER_POOL_ID_STG }}" >> $GITHUB_ENV
            echo "VITE_CLIENT_ID=${{ vars.VITE_CLIENT_ID_STG }}" >> $GITHUB_ENV
            echo "VITE_API_WS_URL=${{ vars.VITE_API_WS_URL_STG }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "VITE_APP_NAME=${{ vars.VITE_APP_NAME_PROD }}" >> $GITHUB_ENV
            echo "VITE_APP_URL=${{ vars.VITE_APP_URL_PROD }}" >> $GITHUB_ENV
            echo "VITE_API_URL=${{ vars.VITE_API_URL_PROD }}" >> $GITHUB_ENV
            echo "VITE_USER_POOL_ID=${{ vars.VITE_USER_POOL_ID_PROD }}" >> $GITHUB_ENV
            echo "VITE_CLIENT_ID=${{ vars.VITE_CLIENT_ID_PROD }}" >> $GITHUB_ENV
            echo "VITE_API_WS_URL=${{ vars.VITE_API_WS_URL_PROD }}" >> $GITHUB_ENV
          fi

      - name: Build frontend
        run: npm run build

      - name: List build output directory
        run: ls -la dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: ./dist

      - name: List contents of dist directory
        run: ls -la dist

      - name: Set AWS Credentials and S3 Bucket
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
            echo "AWS_REGION=${{ secrets.AWS_DEFAULT_REGION_DEV }}" >> $GITHUB_ENV
            echo "S3_BUCKET=${{ vars.S3_BUCKET_DEV }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/demo" ]]; then
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
            echo "AWS_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> $GITHUB_ENV
            echo "S3_BUCKET=${{ vars.S3_BUCKET_STG }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_PROD }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}" >> $GITHUB_ENV
            echo "AWS_REGION=${{ secrets.AWS_DEFAULT_REGION_PROD }}" >> $GITHUB_ENV
            echo "S3_BUCKET=${{ vars.S3_BUCKET_PROD }}" >> $GITHUB_ENV
          fi

      - name: Verify Deployment Secrets
        run: |
          if [ -z "$AWS_ACCESS_KEY_ID" ]; then
            echo "AWS_ACCESS_KEY_ID is not set"
            exit 1
          fi
          if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
            echo "AWS_SECRET_ACCESS_KEY is not set"
            exit 1
          fi
          if [ -z "$AWS_REGION" ]; then
            echo "AWS_REGION is not set"
            exit 1
          fi
          if [ -z "$S3_BUCKET" ]; then
            echo "S3_BUCKET is not set"
            exit 1
          fi

      - name: Deploy to S3 bucket
        run: |
          aws s3 sync dist/ s3://$S3_BUCKET --delete

      - name: Notify on success
        if: success()
        run: echo "Deployment successful!"

      - name: Notify on failure
        if: failure()
        run: echo "Deployment failed!"
